import cv2
import numpy as np
image  = cv2.imread('DSC01606.JPG')
imageapple = cv2.imread('75205.jpg')
imagecolorclassify = cv2.imread('istockphoto-1057506940-612x612.jpg')
hsv_imagecolorclassify = cv2.cvtColor(imagecolorclassify, cv2.COLOR_BGR2HSV)
#I use colorpicker.dev to figure out the HSV values of the colors!!!
red_lower_0 = np.array([0,165,179])
red_upper_0 = np.array([5,255,255])
red_lower_1 = np.array([175,204,204])
red_upper_1 = np.array([180,255,255])
blue_lower_0 = np.array([109,153,153])
blue_upper_0 = np.array([125,255,255])
green_lower_0 = np.array([75/2,0.5*255,0.4*255])
green_upper_0 = np.array([105/2,1*255,1*255])
yellow_lower_0 = np.array([50/2,0.4*255,0.7*255])
yellow_upper_0 = np.array([60/2,1*255,1*255])
orange_lower_0 = np.array([6,int(0.5*255),int(0.7*255)])
orange_upper_0 = np.array([15,1*255,1*255])
purple_lower_0 = np.array([250/2,0.5*255,0.5*255])
purple_upper_0 = np.array([300/2,1*255,1*255])
cyan_lower_0 = np.array([160/2,0.5*255,0.6*255])
cyan_upper_0 = np.array([200/2,1*255,1*255])

mask_red_0 = cv2.inRange(hsv_imagecolorclassify, red_lower_0, red_upper_0)
mask_red_1 = cv2.inRange(hsv_imagecolorclassify, red_lower_1, red_upper_1)
mask_blue_0 = cv2.inRange(hsv_imagecolorclassify, blue_lower_0, blue_upper_0)
mask_green_0 = cv2.inRange(hsv_imagecolorclassify, green_lower_0, green_upper_0)
mask_yellow_0 = cv2.inRange(hsv_imagecolorclassify, yellow_lower_0, yellow_upper_0)
mask_orange_0 = cv2.inRange(hsv_imagecolorclassify, orange_lower_0, orange_upper_0)
mask_purple_0 = cv2.inRange(hsv_imagecolorclassify, purple_lower_0, purple_upper_0)
mask_cyan_0 = cv2.inRange(hsv_imagecolorclassify, cyan_lower_0, cyan_upper_0)
combined_mask_red = cv2.bitwise_or(mask_red_0, mask_red_1)

indices_red_0 = np.where(mask_red_0 == 255)
indices_red_1 = np.where(mask_red_1 == 255) 
indices_blue_0 = np.where(mask_blue_0 == 255)
indices_green_0 = np.where(mask_green_0 == 255)
indices_yellow_0 = np.where(mask_yellow_0 == 255)
indices_orange_0 = np.where(mask_orange_0 == 255)
indices_purple_0 = np.where(mask_purple_0 == 255)
indices_cyan_0 = np.where(mask_cyan_0 == 255)


print('Center (x,y) coordinate of red pixels: (' + str(np.mean(np.mean(indices_red_0[1]) + np.mean(indices_red_1[1]))) + ', ' + str(np.mean(np.mean(indices_red_0[0]) + np.mean(indices_red_1[0]))) + ')')
print('Center (x,y) coordinate of blue pixels: (' + str(np.mean(indices_blue_0[0])) + ', ' + str(np.mean(indices_blue_0[1])) + ')')
print('Center (x,y) coordinate of green pixels: (' + str(np.mean(indices_green_0[0])) + ', ' + str(np.mean(indices_green_0[1])) + ')')
print('Center (x,y) coordinate of yellow pixels: (' + str(np.mean(indices_yellow_0[0])) + ', ' + str(np.mean(indices_yellow_0[1])) + ')')
print('Center (x,y) coordinate of orange pixels: (' + str(np.mean(indices_orange_0[0])) + ', ' + str(np.mean(indices_orange_0[1])) + ')')
print('Center (x,y) coordinate of purple pixels: (' + str(np.mean(indices_purple_0[0])) + ', ' + str(np.mean(indices_purple_0[1])) + ')')
print('Center (x,y) coordinate of cyan pixels: (' + str(np.mean(indices_cyan_0[0])) + ', ' + str(np.mean(indices_cyan_0[1])) + ')')

final_mask_red = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = combined_mask_red)
final_mask_blue = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_blue_0)
final_mask_green = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_green_0)
final_mask_yellow = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_yellow_0)
final_mask_orange = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_orange_0)
final_mask_purple = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_purple_0)
final_mask_cyan = cv2.bitwise_and(imagecolorclassify, imagecolorclassify, mask = mask_cyan_0)

cv2.imwrite('find the red.jpg', final_mask_red)
cv2.imwrite('find the blue.jpg', final_mask_blue)
cv2.imwrite('find the green.jpg', final_mask_green)
cv2.imwrite('find the yellow.jpg', final_mask_yellow)
cv2.imwrite('find the orange.jpg', final_mask_orange)
cv2.imwrite('find the purple.jpg', final_mask_purple)
cv2.imwrite('find the cyan.jpg', final_mask_cyan)

#print(image.shape)
#print(image.dtype)
#print('pixel at Blue (0,0): ' + str(image[0,0,0]))
#print('pixel at Green (0,0): ' + str(image[0,0,1]))
#print('pixel at Red (0,0): ' + str(image[0,0,2]))
#print('pixel at (2000,2000): ' + str(image[2000,2000]))
#image[0:2000,:] = [255, 0, 0]
#imageblackwhite = cv2.imread('DSC01606.JPG')
#cv2.imwrite('change to blue.jpg',image)
#imageblackwhite[:,:,:] = 0
#cv2.imwrite('change to black and white.jpg',imageblackwhite)
'''
hsv_image = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
hsv_image = cv2.blur(hsv_image, (5,5))
apple_hsv_image = cv2.cvtColor(imageapple, cv2.COLOR_BGR2HSV)
lower_bound_apple_1 = np.array([0, 204, 204])
upper_bound_apple_1 = np.array([10, 255, 255])
lower_bound_apple_2 = np.array([175, 204, 204])
upper_bound_apple_2 = np.array([180, 255, 255])
lower_bound = np.array([95,0,0])
upper_bound = np.array([120,255,255])
mask = cv2.inRange(hsv_image, lower_bound, upper_bound)
mask_apple_1 = cv2.inRange(apple_hsv_image, lower_bound_apple_1, upper_bound_apple_1)
mask_apple_2 = cv2.inRange(apple_hsv_image, lower_bound_apple_2, upper_bound_apple_2)
combined_mask_apple = cv2.bitwise_or(mask_apple_1, mask_apple_2)
final_apple = cv2.bitwise_or(imageapple, imageapple, mask = combined_mask_apple)
final_image = cv2.bitwise_and(image, image, mask = mask)
cv2.imwrite('find the blue.jpg', final_image)
cv2.imwrite('find the apple.jpg', final_apple)
'''
